name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write # Required to push to the gh-pages branch
  pages: write  # Required to deploy to GitHub Pages
  id-token: write # Required to authenticate with GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force